In [6]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [7]:
import numpy as np

## DataTypes & Attributes

In [8]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [9]:
type(a1)

numpy.ndarray

In [10]:
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
               [3, 5, 6],
               [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [11]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [12]:
a3

array([[[ 1,  2,  3],
        [ 3,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [13]:
a1.shape

(3,)

In [14]:
a2.shape

(2, 3)

In [15]:
a3.shape

(2, 3, 3)

In [16]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [17]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [18]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [19]:
# Create a DataFrame from a NumPy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating arrays

In [20]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [21]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [24]:
random_array = np.random.randint(0, 10, size = (3, 5))
random_array

array([[7, 3, 9, 0, 3],
       [8, 1, 5, 6, 3],
       [3, 5, 1, 3, 0]])

In [25]:
random_array.size

15

In [26]:
random_array.shape

(3, 5)

In [27]:
np.random.random((5, 3))

array([[0.08404985, 0.61668487, 0.35118347],
       [0.28176591, 0.22593521, 0.25419532],
       [0.33948896, 0.18292397, 0.6086533 ],
       [0.23277851, 0.79843701, 0.459011  ],
       [0.70850052, 0.56979578, 0.13303585]])

In [28]:
np.random.rand(5, 3)

array([[0.12654711, 0.50510085, 0.83408695],
       [0.52403746, 0.0222772 , 0.39639625],
       [0.29539515, 0.99100179, 0.48188305],
       [0.5680333 , 0.05362797, 0.02147805],
       [0.97118149, 0.21984875, 0.54367909]])

In [29]:
np.random.seed(seed=None) # prng + germe (seed) to recreate the same experiment, this could be added before random functions

## Viewing Arrays and Matrices

In [30]:
np.unique(random_array)

array([0, 1, 3, 5, 6, 7, 8, 9])

In [31]:
a1

array([1, 2, 3])

In [32]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [33]:
a3

array([[[ 1,  2,  3],
        [ 3,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [34]:
a1[0]

1

In [35]:
a2[0]

array([1. , 2. , 3.3])

In [36]:
a3[0]

array([[1, 2, 3],
       [3, 5, 6],
       [7, 8, 9]])

In [37]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 3,  5]],

       [[10, 11],
        [13, 14]]])

## Manipulating & comparing arrays

### Arithmetic

In [38]:
a1

array([1, 2, 3])

In [40]:
ones = np.ones(3)

In [41]:
a1 + ones # np.add(a1, ones)

array([2., 3., 4.])

In [42]:
a1 - ones

array([0., 1., 2.])

In [43]:
a1 * ones

array([1., 2., 3.])

In [47]:
a1, a2

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]))

In [46]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [48]:
a1 / ones

array([1., 2., 3.])

In [50]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [51]:
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [52]:
a2 ** 2 # np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [53]:
a1 % 2

array([1, 0, 1])

In [55]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
np.log(a1) # ln

### Aggregation

In [57]:
sum(a1)

6

In [58]:
 np.sum(a1)

6

Use Python's methods ( `sum()` ) on Python datatypes and use NumPy's methods on NumPy arrays ( `np.sum()` )

In [60]:
# Create a massive NumPy array to notice the diffrence
massive_array = np.random.random(100000)
massive_array[:10]

array([0.98190822, 0.55035638, 0.96370358, 0.81906613, 0.28875284,
       0.85736294, 0.21795311, 0.76228948, 0.58860253, 0.84143039])

In [61]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's sum()

8.24 ms ± 158 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
31.3 µs ± 917 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [62]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [63]:
np.mean(a2)

3.6333333333333333

In [64]:
np.max(a2)

6.5

In [65]:
np.min(a2)

1.0

In [66]:
# Standard deviation = a mesure of how spreadout a group of numbers is from the mean

np.std(a2)

1.8226964152656422

In [67]:
# Variance = measure of the average degree to which each number is different to the mean
# Higher variance = wider range o numbers
# Lower variance = lower range of numbers

np.var(a2)

3.3222222222222224

In [68]:
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

In [69]:
np.var(high_var_array), np.var(low_var_array)

(4296133.472222221, 8.0)

In [73]:
np.std(high_var_array), np.std(low_var_array)

(2072.711623024829, 2.8284271247461903)

In [74]:
np.mean(high_var_array), np.mean(low_var_array)

(1600.1666666666667, 6.0)

### Resape and Transpose

In [81]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimension and works its way left. Two dimensions are compatible when

they are equal, or

one of them is 1.

In [85]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [83]:
a2_reshape = a2.reshape(2, 3, 1)
a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [84]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  6. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [86]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [88]:
# Transpose
a2.T, a2.T.shape

(array([[1. , 4. ],
        [2. , 5. ],
        [3.3, 6.5]]),
 (3, 2))

## Dot product

In [90]:
np.random.seed(0)

mat1 = np.random.randint(10, size = (5, 3))
mat2 = np.random.randint(10, size = (5, 3))

mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [91]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [92]:
# Element-wise multiplication (Hadamard product)

mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [94]:
# Dot product (Produit scalaire)
mat3 = np.dot(mat1, mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

## Comparison Operators

In [95]:
a1

array([1, 2, 3])

In [96]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [98]:
a1 >= a2

array([[ True,  True, False],
       [False, False, False]])

In [99]:
a1 > 5

array([False, False, False])

In [100]:
a1 == a1

array([ True,  True,  True])

In [101]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

## Sorting arrays

In [103]:
random_array = np.random.randint(10, size = (3, 5))
random_array

array([[2, 3, 8, 1, 3],
       [3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7]])

In [105]:
np.sort(random_array)

array([[1, 2, 3, 3, 8],
       [0, 1, 3, 3, 7],
       [0, 4, 7, 9, 9]])

In [106]:
np.argsort(random_array) # sort by index

array([[3, 0, 1, 4, 2],
       [3, 4, 0, 1, 2],
       [2, 3, 4, 0, 1]])

In [107]:
np.argmin(random_array)

8

In [114]:
random_array

array([[2, 3, 8, 1, 3],
       [3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7]])

In [113]:
np.argmax(random_array, axis=1)

array([2, 2, 0])